# tidyr

More details in [https://tidyr.tidyverse.org/articles/nest.html](https://tidyr.tidyverse.org/articles/nest.html)

## nest()

```{r}
library(tidyverse)

mtcars %>% 
  group_by(cyl) %>% 
  nest() 

um<- mtcars %>% 
  group_by(cyl) %>% 
  nest() %>%
  mutate(
    linMod = map(data, ~lm(mpg ~ wt, data = .)),
    coeffs = map(linMod, coefficients),
    slope = map_dbl(coeffs, 2))
um
um$linMod
um$coeffs
um$slope


um$linMod[[1]]


dois<- mtcars %>% 
  group_by(cyl) %>% 
  nest() %>% 
  mutate(model = map(data, function(df) lm(mpg ~ wt, data = df)))
dois

dois$cyl
dois$data
dois$model

dois$model[[3]]


tres<- dois %>% 
  mutate(model = map(model, predict))

tres

tres$model
tres$model[[3]]
```

## unnest()

```{r}
um %>% 
  unnest(data)
```


## Exemplos da ajuda do R

```{r}
df <- tibble(x = c(1, 1, 1, 2, 2, 3), 
             y = 1:6, 
             z = 6:1)
df
# Note that we get one row of output for each unique combination of
# non-nested variables
df %>% 
  nest(data = c(y, z))

# chop does something similar, but retains individual columns
df %>% 
  chop(c(y, z))

# use tidyselect syntax and helpers, just like in dplyr::select()
df %>% 
  nest(data = any_of(c("y", "z")))

iris %>% 
  nest(data = !Species)

nest_vars <- names(iris)[1:4]
iris %>% 
  nest(data = any_of(nest_vars))

iris %>%
  nest(petal = starts_with("Petal"), sepal = starts_with("Sepal"))

iris %>%
  nest(width = contains("Width"), length = contains("Length"))

# Nesting a grouped data frame nests all variables apart from the group vars
fish_encounters %>%
  group_by(fish) %>%
  nest()

# Nesting is often useful for creating per group models
mtcars %>%
  group_by(cyl) %>%
  nest() %>%
  mutate(models = lapply(data, function(df) lm(mpg ~ wt, data = df)))

# unnest() is primarily designed to work with lists of data frames
df <- tibble(
  x = 1:3,
  y = list(
    NULL,
    tibble(a = 1, b = 2),
    tibble(a = 1:3, b = 3:1)
  )
)

df %>% 
  unnest(y)

df %>% 
  unnest(y, keep_empty = TRUE)

# If you have lists of lists, or lists of atomic vectors, instead
# see hoist(), unnest_wider(), and unnest_longer()

#' # You can unnest multiple columns simultaneously
df <- tibble(
 a = list(c("a", "b"), "c"),
 b = list(1:2, 3),
 c = c(11, 22)
)
df

df %>% 
  unnest(c(a, b))

# Compare with unnesting one column at a time, which generates
# the Cartesian product
df %>% 
  unnest(a) %>% 
  unnest(b)
```

## Mais detalhes

[https://github.com/tidymodels/broom/blob/main/vignettes/broom_and_dplyr.Rmd](https://github.com/tidymodels/broom/blob/main/vignettes/broom_and_dplyr.Rmd)

